--- 
title: "Twitter Sentiment Analysis"
author: "Sung Jun Won(sw3049), Elin Kim(hk3175), Alex Kita(ak4729)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

People have varied opinions about the COVID-19, and many have expressed their thoughts regarding COVID-19 on Twitter. Some are overly anxious about the impact of the virus while others are optimistic. We wanted to explore how some influential groups of people/organizations - namely celebrities, medical associations, and politicians - reacted to COVID-19 from the beginning of COVID-19 crisis in March 2020 up to the current date. We mainly focused on analyzing sentiments of the tweets from those groups to learn how the reactions to COVID-19 were different or on the same page between the groups as well as within the groups.

We laid out our sentiment analysis project in a number of steps. We start by introducing how we collected the Twitter data using Twitter API, followed by how we cleaned and transformed the data to fit the purpose of our project. Then we explain and graphically show how we dealt with missing values. The next part, which we think is the major part of the project, shows various graphs that explains trends of sentiment changes over time between the groups and within the groups. We also implemented the interactive graph that allows the user to choose which group's sentiment score changes over time to display. The last part of the project discusses what we have learned in the process and what we can potentially do to develop the sentiment analysis further. 

book URL: https://twittersentimentanalyze.github.io/twittersentiment/

This repo was initially generated from a bookdown template available here: https://github.com/jtr13/EDAVtemplate